language: generic
sudo: required
services:
  - docker

# Build testing container
before_install:
  - docker build -t brungo1995/test-container -f Dockerfile.dev .

# Run Tests
script:
  - docker run -e CI=true brungo1995/test-container npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "af-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-af-south-1-818961183844"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
